config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/about'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
 
  def about
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<%= link_to 'Strona główna', root_path %>
<%= link_to 'O mnie', home_about_path %>

app/views/home/about.html.erb
<h1> O mnie...</h1>
<p> Nazywam się Paweł Rotko i tworzę aplikację obrazkową </p>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>To jest moja strona internetowa</h1>
<p>To będzie działać w przyszłości</p>
<%= link_to 'O mnie', home_about_path, class: 'btn btn-default btn-lg' %>
<%= link_to 'Strona główna', root_path, class: 'btn btn-primary' %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'home/header'%>
		
	<div class="container">	
    	<%= yield %>
	</div>
		
		
  </body>
	  
</html>